### ISSUE TITLE
socket io problem

### ISSUE THREAD

**Issue by hieutrluu** [janhvipatil/Raven#125]
Hi @janhvipatil, thank you and the team for creating a great app

I am trying to run the app in dev mode in `frappe_docker` development running `yarn dev` on raven-app

- frappe version: v14.26.3
- my site_config.json
```
{
 ...
 "db_type": "mariadb",
 "developer_mode": 1,
 "ignore_csrf": 1,
 "allow_cors": "*",
 "monitor": 1,
 "nginx_port": 8000
}
```

I have also changed the socketio port to 9000
```
import { io } from 'socket.io-client'

let socket_port = import.meta.env.VITE_SOCKET_PORT ?? "9000"
let host = window.location.hostname;
let port = window.location.port ? `:${socket_port}` : '';
let protocol = port ? 'http' : 'https';
let url = `${protocol}://${host}${port}`;
let socket = io(url, { withCredentials: true })

export default socket;
```

The app run, however the chat is not in realtime. Whenever I type a message I have to refresh the web app to see the new message.

This is the console and the error in the cosle some time I see the error, sometime not.
<img width="1728" alt="Screenshot 2023-03-08 at 06 14 39" src="https://user-images.githubusercontent.com/32662977/223575608-17c1f033-c41b-4984-a82a-4005e33e7912.png">
The stack trace of the error
<img width="1728" alt="Screenshot 2023-03-08 at 06 16 22" src="https://user-images.githubusercontent.com/32662977/223576247-8af5875d-867c-4232-8d13-fa4bc21ec4fe.png">
The network tab of devtool (socketio connection seem to be ok)
<img width="876" alt="Screenshot 2023-03-08 at 07 00 16" src="https://user-images.githubusercontent.com/32662977/223583358-f45fe6c1-3976-4c73-a502-f82e4c2fa87e.png">

I have also tried to restart the containers and setup debugger in the javascript file but no luck of understanding it yet

Any pointer on what should I do ?
Best regards

**Comment by hieutrluu** [comment]
Hi @nikkothari22, any chance that u can help me with this :p ?

**Comment by nikkothari22** [comment]
Hi @hieutrluu ,

I haven't tried running the app using Docker - so I don't know why it's not connecting to socket. 

Have you tried running it without Docker? 

Can you also share your entire common_site_config.json and site_config.json?

**Comment by hieutrluu** [comment]
Hi @nikkothari22 
these are the file:

common_site_config.json
```
{
 "background_workers": 1,
 "db_host": "mariadb",
 "file_watcher_port": 6787,
 "frappe_user": "frappe",
 "gunicorn_workers": 13,
 "live_reload": true,
 "rebase_on_pull": false,
 "redis_cache": "redis://redis-cache:6379",
 "redis_queue": "redis://redis-queue:6379",
 "redis_socketio": "redis://redis-socketio:6379",
 "restart_supervisor_on_update": false,
 "restart_systemd_on_update": false,
 "root_login": "root",
 "root_password": "123",
 "serve_default_site": true,
 "shallow_clone": true,
 "socketio_port": 9000,
 "use_redis_auth": false,
 "webserver_port": 8000
}
```

site_config.json
```
{
 "background_workers": 1,
 "db_host": "mariadb",
 "file_watcher_port": 6787,
 "frappe_user": "frappe",
 "gunicorn_workers": 13,
 "live_reload": true,
 "rebase_on_pull": false,
 "redis_cache": "redis://redis-cache:6379",
 "redis_queue": "redis://redis-queue:6379",
 "redis_socketio": "redis://redis-socketio:6379",
 "restart_supervisor_on_update": false,
 "restart_systemd_on_update": false,
 "root_login": "root",
 "root_password": "123",
 "serve_default_site": true,
 "shallow_clone": true,
 "socketio_port": 9000,
 "use_redis_auth": false,
 "webserver_port": 8000
}
```

I don't have current_site.txt
<img width="561" alt="Screenshot 2023-03-08 at 13 25 39" src="https://user-images.githubusercontent.com/32662977/223635653-b0d66375-fe0a-439c-b4b8-0b83466494ac.png">

**Comment by hieutrluu** [comment]
@nikkothari22 I'm curious on how do you setup your dev environment ?
install bench directly to your local machine ?

**Comment by nikkothari22** [comment]
> @nikkothari22 I'm curious on how do you setup your dev environment ?
> 
> install bench directly to your local machine ?

Yeah. We install it directly on the local machine. I don't have much experience of using Frappe with Docker to be honest.

**Comment by hieutrluu** [comment]
the problem was "The protocol version is not supported by the server. Support for Socket.IO v2 clients must be explicitly enabled with the [allowEIO3](https://socket.io/docs/v3/server-initialization/#allowEIO3) option"
https://socket.io/docs/v3/troubleshooting-connection-issues/

update socketio.js in frappe
```
const io = require("socket.io")(conf.socketio_port, {
	allowEIO3: true, // false by default
	cors: {
		// Should be fine since we are ensuring whether hostname and origin are same before adding setting listeners for s socket
		origin: true,
		credentials: true,
	},
});
```

**Comment by fzhan** [comment]
@hieutrluu are you using the pwd.yml setup in https://github.com/frappe/frappe_docker/blob/main/pwd.yml ?
